version: 0.2

# Assume we are using Ubuntu/7.0 codebuild image aka aws/codebuild/standard:7.0

phases:
  pre_build:
    commands:
      # This is set as an environment variable in the build project.
      # This makes it easier to keep account ids out of the files.
      - echo "AccountID=$ACCOUNTID"
      - aws --version
      
      - docker --version
      
      # Which shell are we using?
      - echo "Using shell..."
      - ls -lha $(which sh)
      # What's the build environment public ip?
      # (We need to be able to reach the LB in front of the web app by the way)
      - curl checkip.amazonaws.com  
      
      - echo Logging in to Amazon ECR...
      # Must login to private repo 
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      #
      - REPOSITORY_URI=$ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/a-new-startup-testing-image
  build:
    on-failure: ABORT
    commands:
      - echo Testing started on `date`.
      # Testing is this simple, just run the pre-built container.
      # This will use the exit code from the Python script
      # because we have on-failure set to ABORT - if this fails, it will fail the build
      - docker run $REPOSITORY_URI:latest
      
  post_build:
    commands:
      - echo Testing is completed on `date`
artifacts:
    files: 
      - report.txt
      